name: Release
on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: ['1.11', '1.12', '1.13']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go run main.go
  build:
    runs-on: ubuntu-18.04
    needs: test
    strategy:
      matrix:
        go: ['1.11', '1.12', '1.13']
    name: Go ${{ matrix.go }} build
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go run main.go
  release:
    runs-on: ubuntu-18.04
    needs: [test, build]
    steps:
      - uses: brpaz/action-semantic-release@v1
        with:
          dry_run: "false"
          install_plugins: "semantic-release-docker semantic-release-gcr"
          branch: master
